# This is a basic workflow to help you get started with Actions

name: Trigger Jenkins Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    trigger-jenkins:
      runs-on: self-hosted

      steps:
        - name: Trigger Jenkins Build
          run: |
            curl -X POST "$JENKINS_URL" \
            --user "$JENKINS_USER:$JENKINS_TOKEN"
          env:
            JENKINS_URL: ${{ secrets.JENKINS_URL }} 
            JENKINS_USER: ${{ secrets.JENKINS_USER }} 
            JENKINS_TOKEM: ${{ secrets.JENKINS_TOKEN }} 
            
